import { defineCollection } from 'astro:content';
import { docsLoader, i18nLoader } from '@astrojs/starlight/loaders';
import { docsSchema, i18nSchema } from '@astrojs/starlight/schema';
import { z } from 'astro/zod';

export const collections = {
	docs: defineCollection({
		loader: docsLoader(),
		schema: docsSchema({
			extend: z.object({
				hero: z
					.object({
						subtitle: z.string().optional(),
					})
					.optional(),
			}),
		}),
	}),
	i18n: defineCollection({
		loader: i18nLoader(),
		schema: i18nSchema({
			extend: z.object({
				'tab.play': z.string(),
				'tab.rules': z.string(),
				'tab.lore': z.string(),
				'home.subtitle': z.string(),
				'home.tagline': z.string(),
				'home.action.learn': z.string(),
				'home.action.round': z.string(),
				'home.action.guided': z.string(),
				'guided.progress': z.string(),
				'guided.progressPhase': z.string(),
				'guided.phase.setup': z.string(),
				'guided.phase.spring': z.string(),
				'guided.phase.summer': z.string(),
				'guided.phase.autumn': z.string(),
				'guided.phase.winter': z.string(),
				'guided.back': z.string(),
				'guided.next': z.string(),
				'guided.learnMore': z.string(),
				'guided.mode.title': z.string(),
				'guided.mode.intro': z.string(),
				'guided.mode.quickplay': z.string(),
				'guided.mode.quickplayDesc': z.string(),
				'guided.mode.standard': z.string(),
				'guided.mode.standardDesc': z.string(),
				'guided.mode.magnus': z.string(),
				'guided.mode.magnusDesc': z.string(),
				'guided.mode.confirm': z.string(),
				'guided.resume.title': z.string(),
				'guided.resume.body': z.string(),
				'guided.resume.continue': z.string(),
				'guided.resume.fresh': z.string(),
				'guided.complete.cta': z.string(),
				'guided.complete.continuePlaying': z.string(),
				'guided.startOver': z.string(),
				'guided.context.title': z.string(),
				'guided.context.empty': z.string(),
				'guided.context.openFull': z.string(),
				'guided.crucible.buildType': z.string(),
				'guided.nav.trigger': z.string(),
				'guided.nav.title': z.string(),
				'guided.nav.roundIntro': z.string(),
				'guided.nav.roundEnd': z.string(),
				'home.intro.summary': z.string(),
				'home.intro.playersLabel': z.string(),
				'home.intro.playersValue': z.string(),
				'home.intro.playTimeLabel': z.string(),
				'home.intro.playTimeValue': z.string(),
				'home.social.aria': z.string(),
				'home.social.x': z.string(),
				'home.social.discord': z.string(),
				'home.copyright': z.string(),
				'glossary.intro': z.string(),
				'flow.required': z.string(),
				'flow.optional': z.string(),
				'flow.choice': z.string(),
				'flow.sequence': z.string(),
				'flow.appliesWhen': z.string(),
				'flow.likelySkip': z.string(),
				'flow.readMore': z.string(),
				'flow.pickPrompt': z.string(),
				'flow.stonePickerTitle': z.string(),
				'flow.stoneAll': z.string(),
				'flow.stoneStasis': z.string(),
				'flow.stoneForgingNew': z.string(),
				'flow.stoneForgingReady': z.string(),
				'flow.stoneNotInForge': z.string(),
				'flow.processionLabel': z.string(),
				'flow.passLikelySkip': z.string(),
				'flow.wizardBack': z.string(),
				'flow.wizardContinue': z.string(),
				'flow.wizardDone': z.string(),
				'flow.wizardStepOf': z.string(),
				'flow.yes': z.string(),
				'flow.noSkip': z.string(),
				'flow.autumnDoneMessage': z.string(),
				'flow.autumnRestartLabel': z.string(),
				'flow.autumnOppositionPrompt': z.string(),
				'flow.autumnLightCauldronsPrompt': z.string(),
				'flow.autumnTemperPrompt': z.string(),
				'flow.autumnFirePrompt': z.string(),
			'flow.winterWagerPrompt': z.string(),
			'a11y.menuLabel': z.string(),
			'a11y.themeLabel': z.string(),
			'a11y.themeDark': z.string(),
			'a11y.themeLight': z.string(),
			'a11y.themeSystem': z.string(),
			'a11y.fontSizeLabel': z.string(),
			'a11y.fontDefault': z.string(),
			'a11y.fontLarge': z.string(),
			'a11y.fontLarger': z.string(),
		}),
		}),
	}),
};
