import { defineCollection } from 'astro:content';
import { docsLoader, i18nLoader } from '@astrojs/starlight/loaders';
import { docsSchema, i18nSchema } from '@astrojs/starlight/schema';
import { z } from 'astro/zod';

export const collections = {
	docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
	i18n: defineCollection({
		loader: i18nLoader(),
		schema: i18nSchema({
			extend: z.object({
				'tab.learn': z.string(),
				'tab.play': z.string(),
				'tab.reference': z.string(),
				'tab.glossary': z.string(),
				'tab.guided': z.string(),
				'gameMode.modifiers': z.string(),
				'gameMode.quickplay': z.string(),
				'gameMode.magnus': z.string(),
				'home.tagline': z.string(),
				'home.action.learn': z.string(),
				'home.action.round': z.string(),
				'home.action.guided': z.string(),
				'guided.progress': z.string(),
				'guided.progressPhase': z.string(),
				'guided.phase.setup': z.string(),
				'guided.phase.spring': z.string(),
				'guided.phase.summer': z.string(),
				'guided.phase.autumn': z.string(),
				'guided.phase.winter': z.string(),
				'guided.back': z.string(),
				'guided.next': z.string(),
				'guided.learnMore': z.string(),
				'guided.mode.title': z.string(),
				'guided.mode.intro': z.string(),
				'guided.mode.quickplay': z.string(),
				'guided.mode.quickplayDesc': z.string(),
				'guided.mode.standard': z.string(),
				'guided.mode.standardDesc': z.string(),
				'guided.mode.magnus': z.string(),
				'guided.mode.magnusDesc': z.string(),
				'guided.mode.confirm': z.string(),
				'guided.resume.title': z.string(),
				'guided.resume.body': z.string(),
				'guided.resume.continue': z.string(),
				'guided.resume.fresh': z.string(),
				'guided.complete.cta': z.string(),
				'guided.startOver': z.string(),
				'guided.context.title': z.string(),
				'guided.context.empty': z.string(),
				'guided.context.openFull': z.string(),
				'guided.crucible.buildType': z.string(),
				'home.intro.summary': z.string(),
				'home.intro.playersLabel': z.string(),
				'home.intro.playersValue': z.string(),
				'home.intro.playTimeLabel': z.string(),
				'home.intro.playTimeValue': z.string(),
				'home.social.aria': z.string(),
				'home.social.instagram': z.string(),
				'home.social.facebook': z.string(),
				'home.social.youtube': z.string(),
				'home.copyright': z.string(),
				'glossary.intro': z.string(),
				'flow.required': z.string(),
				'flow.optional': z.string(),
				'flow.choice': z.string(),
				'flow.sequence': z.string(),
				'flow.appliesWhen': z.string(),
				'flow.likelySkip': z.string(),
				'flow.readMore': z.string(),
				'flow.pickPrompt': z.string(),
				'flow.stonePickerTitle': z.string(),
				'flow.stoneAll': z.string(),
				'flow.stoneStasis': z.string(),
				'flow.stoneForgingNew': z.string(),
				'flow.stoneForgingReady': z.string(),
				'flow.stoneNotInForge': z.string(),
				'flow.processionLabel': z.string(),
				'flow.passLikelySkip': z.string(),
			}),
		}),
	}),
};
