import { defineCollection } from 'astro:content';
import { docsLoader, i18nLoader } from '@astrojs/starlight/loaders';
import { docsSchema, i18nSchema } from '@astrojs/starlight/schema';
import { z } from 'astro/zod';

export const collections = {
	docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
	i18n: defineCollection({
		loader: i18nLoader(),
		schema: i18nSchema({
			extend: z.object({
				'tab.learn': z.string(),
				'tab.play': z.string(),
				'tab.reference': z.string(),
				'tab.glossary': z.string(),
				'tab.guided': z.string(),
				'gameMode.modifiers': z.string(),
				'gameMode.quickplay': z.string(),
				'gameMode.magnus': z.string(),
				'home.tagline': z.string(),
				'home.action.learn': z.string(),
				'home.action.round': z.string(),
				'home.action.guided': z.string(),
				'guided.progress': z.string(),
				'guided.progressPhase': z.string(),
				'guided.phase.setup': z.string(),
				'guided.phase.spring': z.string(),
				'guided.phase.summer': z.string(),
				'guided.phase.autumn': z.string(),
				'guided.phase.winter': z.string(),
				'guided.back': z.string(),
				'guided.next': z.string(),
				'guided.learnMore': z.string(),
				'guided.mode.title': z.string(),
				'guided.mode.intro': z.string(),
				'guided.mode.quickplay': z.string(),
				'guided.mode.quickplayDesc': z.string(),
				'guided.mode.standard': z.string(),
				'guided.mode.standardDesc': z.string(),
				'guided.mode.magnus': z.string(),
				'guided.mode.magnusDesc': z.string(),
				'guided.mode.confirm': z.string(),
				'guided.resume.title': z.string(),
				'guided.resume.body': z.string(),
				'guided.resume.continue': z.string(),
				'guided.resume.fresh': z.string(),
				'guided.complete.cta': z.string(),
				'guided.startOver': z.string(),
				'guided.context.title': z.string(),
				'guided.context.empty': z.string(),
				'guided.context.openFull': z.string(),
				'guided.crucible.buildType': z.string(),
				'home.sectionTitle': z.string(),
				'home.card.search.title': z.string(),
				'home.card.search.body': z.string(),
				'home.card.tabs.title': z.string(),
				'home.card.tabs.body': z.string(),
				'home.card.share.title': z.string(),
				'home.card.share.body': z.string(),
				'home.card.offline.title': z.string(),
				'home.card.offline.body': z.string(),
				'home.card.modes.title': z.string(),
				'home.card.modes.body': z.string(),
				'home.card.newPlayers.title': z.string(),
				'home.card.newPlayers.body': z.string(),
				'home.footer': z.string(),
				'glossary.intro': z.string(),
			}),
		}),
	}),
};
